-- =============================================================
--  DUVID GEOGRAFIA — Tabela de tags canônicas
--  Gerada automaticamente a partir dos JSONs das questões
--  Execute uma vez no banco de produção
-- =============================================================

CREATE TABLE IF NOT EXISTS tags (
    id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome       VARCHAR(120) NOT NULL,
    slug       VARCHAR(120) NOT NULL,
    criado_em  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO tags (nome, slug) VALUES
    ('11 de setembro', '11-de-setembro'),
    ('1940-1980', '1940-1980'),
    ('2003', '2003'),
    ('ab\'saber', 'ab-saber'),
    ('abc paulista', 'abc-paulista'),
    ('abertura econômica', 'abertura-econômica'),
    ('acnur', 'acnur'),
    ('acordo comercial', 'acordo-comercial'),
    ('acordo de paz', 'acordo-de-paz'),
    ('acordos ambientais internacionais', 'acordos-ambientais-internacionais'),
    ('adaptação', 'adaptação'),
    ('adaptações vegetais', 'adaptações-vegetais'),
    ('adesão', 'adesão'),
    ('afeganistão', 'afeganistão'),
    ('afirmativas incorretas', 'afirmativas-incorretas'),
    ('africanos no brasil', 'africanos-no-brasil'),
    ('agentes endógenos', 'agentes-endógenos'),
    ('agentes externos', 'agentes-externos'),
    ('agentes exógenos', 'agentes-exógenos'),
    ('agentes formadores do relevo', 'agentes-formadores-do-relevo'),
    ('agentes internos', 'agentes-internos'),
    ('aglomerações urbanas', 'aglomerações-urbanas'),
    ('agreste nordestino', 'agreste-nordestino'),
    ('agricultura', 'agricultura'),
    ('agricultura familiar', 'agricultura-familiar'),
    ('agricultura intensiva', 'agricultura-intensiva'),
    ('agricultura moderna', 'agricultura-moderna'),
    ('agricultura mundial', 'agricultura-mundial'),
    ('agricultura orgânica', 'agricultura-orgânica'),
    ('agricultura tradicional', 'agricultura-tradicional'),
    ('agricultura urbana', 'agricultura-urbana'),
    ('agroecologia', 'agroecologia'),
    ('agroindústria', 'agroindústria'),
    ('agronegócio', 'agronegócio'),
    ('agropecuária', 'agropecuária'),
    ('ajuste fiscal', 'ajuste-fiscal'),
    ('alagamentos', 'alagamentos'),
    ('alemanha', 'alemanha'),
    ('aliança do pacífico', 'aliança-do-pacífico'),
    ('altitude', 'altitude'),
    ('alumínio', 'alumínio'),
    ('amazônia', 'amazônia'),
    ('ampliação', 'ampliação'),
    ('américa', 'américa'),
    ('américa central', 'américa-central'),
    ('américa do norte', 'américa-do-norte'),
    ('américa do sul', 'américa-do-sul'),
    ('américa latina', 'américa-latina'),
    ('américa platina', 'américa-platina'),
    ('anamorfose', 'anamorfose'),
    ('andes', 'andes'),
    ('anexação', 'anexação'),
    ('angola', 'angola'),
    ('animação', 'animação'),
    ('anos 1980', 'anos-1980'),
    ('antártica', 'antártica'),
    ('antípodas', 'antípodas'),
    ('análise climática', 'análise-climática'),
    ('análise crítica', 'análise-crítica'),
    ('análise espacial', 'análise-espacial'),
    ('apa', 'apa'),
    ('apartheid', 'apartheid'),
    ('app', 'app'),
    ('aquecimento global', 'aquecimento-global'),
    ('aquífero guarani', 'aquífero-guarani'),
    ('aquíferos', 'aquíferos'),
    ('argentina', 'argentina'),
    ('arquipélago', 'arquipélago'),
    ('aspectos físicos', 'aspectos-físicos'),
    ('assad', 'assad'),
    ('associação de conceitos', 'associação-de-conceitos'),
    ('ataque químico', 'ataque-químico'),
    ('atividade industrial', 'atividade-industrial'),
    ('atividades humanas', 'atividades-humanas'),
    ('atmosfera', 'atmosfera'),
    ('austrália', 'austrália'),
    ('ausência de cordilheiras', 'ausência-de-cordilheiras'),
    ('automação', 'automação'),
    ('autonomia', 'autonomia'),
    ('autonomia regional', 'autonomia-regional'),
    ('avanço técnico', 'avanço-técnico'),
    ('bacias hidrográficas', 'bacias-hidrográficas'),
    ('bacias sedimentares', 'bacias-sedimentares'),
    ('balança comercial', 'balança-comercial'),
    ('banco mundial', 'banco-mundial'),
    ('bandeira', 'bandeira'),
    ('bandeiras paulistas', 'bandeiras-paulistas'),
    ('barragem', 'barragem'),
    ('barreiras alfandegárias', 'barreiras-alfandegárias'),
    ('bauxita', 'bauxita'),
    ('belo monte', 'belo-monte'),
    ('belt system', 'belt-system'),
    ('biocombustíveis', 'biocombustíveis'),
    ('biodiesel', 'biodiesel'),
    ('biodiversidade', 'biodiversidade'),
    ('bioenergia', 'bioenergia'),
    ('biogeografia', 'biogeografia'),
    ('bioma', 'bioma'),
    ('bioma amazônia', 'bioma-amazônia'),
    ('bioma mata atlântica', 'bioma-mata-atlântica'),
    ('biomas brasileiros', 'biomas-brasileiros'),
    ('biomas mundiais', 'biomas-mundiais'),
    ('biomassa', 'biomassa'),
    ('biosfera', 'biosfera'),
    ('biotecnologia', 'biotecnologia'),
    ('bipolaridade', 'bipolaridade'),
    ('blocos', 'blocos'),
    ('blocos econômicos', 'blocos-econômicos'),
    ('blocos militares', 'blocos-militares'),
    ('blocos mundiais', 'blocos-mundiais'),
    ('boko haram', 'boko-haram'),
    ('bolívia', 'bolívia'),
    ('brasil', 'brasil'),
    ('brasil-bolívia', 'brasil-bolívia'),
    ('brasília', 'brasília'),
    ('brexit', 'brexit'),
    ('brics', 'brics'),
    ('brisa marítima', 'brisa-marítima'),
    ('brumadinho', 'brumadinho'),
    ('bálcãs', 'bálcãs'),
    ('bônus demográfico', 'bônus-demográfico'),
    ('caatinga', 'caatinga'),
    ('cabotagem', 'cabotagem'),
    ('cadeia produtiva global', 'cadeia-produtiva-global'),
    ('caloria', 'caloria'),
    ('camada de ozônio', 'camada-de-ozônio'),
    ('camadas da atmosfera', 'camadas-da-atmosfera'),
    ('camadas da terra', 'camadas-da-terra'),
    ('campo', 'campo'),
    ('cana-de-açúcar', 'cana-de-açúcar'),
    ('canadá', 'canadá'),
    ('canal artificial', 'canal-artificial'),
    ('canalização de rios', 'canalização-de-rios'),
    ('candidatura', 'candidatura'),
    ('capacidade instalada', 'capacidade-instalada'),
    ('capital especulativo', 'capital-especulativo'),
    ('capital estrangeiro', 'capital-estrangeiro'),
    ('capital financeiro', 'capital-financeiro'),
    ('capitalismo', 'capitalismo'),
    ('capitalismo financeiro', 'capitalismo-financeiro'),
    ('capitalismo monopolista', 'capitalismo-monopolista'),
    ('características', 'características'),
    ('características climáticas', 'características-climáticas'),
    ('características do brasil', 'características-do-brasil'),
    ('características dos biomas', 'características-dos-biomas'),
    ('características econômicas', 'características-econômicas'),
    ('características geográficas', 'características-geográficas'),
    ('características gerais', 'características-gerais'),
    ('características naturais', 'características-naturais'),
    ('características regionais', 'características-regionais'),
    ('carga', 'carga'),
    ('caribe', 'caribe'),
    ('carta topográfica', 'carta-topográfica'),
    ('carteira de trabalho', 'carteira-de-trabalho'),
    ('cartografia', 'cartografia'),
    ('cartografia crítica', 'cartografia-crítica'),
    ('cartografia temática', 'cartografia-temática'),
    ('cartografia urbana', 'cartografia-urbana'),
    ('carvão', 'carvão'),
    ('carvão mineral', 'carvão-mineral'),
    ('carência alimentar', 'carência-alimentar'),
    ('catalunha', 'catalunha'),
    ('categorias geográficas', 'categorias-geográficas'),
    ('causas', 'causas'),
    ('caxemira', 'caxemira'),
    ('censo demográfico', 'censo-demográfico'),
    ('centralidade urbana', 'centralidade-urbana'),
    ('centro-sul', 'centro-sul'),
    ('centros de decisão', 'centros-de-decisão'),
    ('centros urbanos', 'centros-urbanos'),
    ('cerrado', 'cerrado'),
    ('cfc', 'cfc'),
    ('chapadas', 'chapadas'),
    ('chapadão', 'chapadão'),
    ('charge', 'charge'),
    ('chile', 'chile'),
    ('china', 'china'),
    ('chuva ácida', 'chuva-ácida'),
    ('ciclo da borracha', 'ciclo-da-borracha'),
    ('ciclo das rochas', 'ciclo-das-rochas'),
    ('ciclo do ouro', 'ciclo-do-ouro'),
    ('ciclo energético', 'ciclo-energético'),
    ('ciclo hidrológico', 'ciclo-hidrológico'),
    ('ciclones', 'ciclones'),
    ('ciclos econômicos', 'ciclos-econômicos'),
    ('cidade', 'cidade'),
    ('cidade e natureza', 'cidade-e-natureza'),
    ('cidades contemporâneas', 'cidades-contemporâneas'),
    ('cidades globais', 'cidades-globais'),
    ('cidades médias', 'cidades-médias'),
    ('circulação oceânica', 'circulação-oceânica'),
    ('ciência geográfica', 'ciência-geográfica'),
    ('classificação', 'classificação'),
    ('classificação climática', 'classificação-climática'),
    ('classificação do relevo', 'classificação-do-relevo'),
    ('classificação industrial', 'classificação-industrial'),
    ('clima', 'clima'),
    ('clima continental', 'clima-continental'),
    ('clima de são paulo', 'clima-de-são-paulo'),
    ('clima do brasil', 'clima-do-brasil'),
    ('clima polar', 'clima-polar'),
    ('clima sazonal', 'clima-sazonal'),
    ('clima subtropical', 'clima-subtropical'),
    ('clima tropical', 'clima-tropical'),
    ('clima urbano', 'clima-urbano'),
    ('clima árido', 'clima-árido'),
    ('climograma', 'climograma'),
    ('coeficiente de gini', 'coeficiente-de-gini'),
    ('colonialismo', 'colonialismo'),
    ('colonialismo britânico', 'colonialismo-britânico'),
    ('colonização', 'colonização'),
    ('colonização do sul', 'colonização-do-sul'),
    ('colômbia', 'colômbia'),
    ('combustíveis fósseis', 'combustíveis-fósseis'),
    ('comitê de bacia', 'comitê-de-bacia'),
    ('commodities', 'commodities'),
    ('commoditização', 'commoditização'),
    ('comparação', 'comparação'),
    ('comparação energética', 'comparação-energética'),
    ('comparação entre países', 'comparação-entre-países'),
    ('comparação global', 'comparação-global'),
    ('compartimentos de relevo', 'compartimentos-de-relevo'),
    ('compartimentos do relevo', 'compartimentos-do-relevo'),
    ('compensação ambiental', 'compensação-ambiental'),
    ('compensação financeira', 'compensação-financeira'),
    ('competição', 'competição'),
    ('competição empresarial', 'competição-empresarial'),
    ('complexidade urbana', 'complexidade-urbana'),
    ('complexos regionais', 'complexos-regionais'),
    ('comportamento demográfico', 'comportamento-demográfico'),
    ('composição atmosférica', 'composição-atmosférica'),
    ('comunicação', 'comunicação'),
    ('comércio bilateral', 'comércio-bilateral'),
    ('comércio eletrônico', 'comércio-eletrônico'),
    ('comércio exterior', 'comércio-exterior'),
    ('comércio global', 'comércio-global'),
    ('comércio internacional', 'comércio-internacional'),
    ('comércio mundial', 'comércio-mundial'),
    ('conceito geográfico', 'conceito-geográfico'),
    ('conceitos demográficos', 'conceitos-demográficos'),
    ('conceitos geográficos', 'conceitos-geográficos'),
    ('concentração de terras', 'concentração-de-terras'),
    ('concentração fundiária', 'concentração-fundiária'),
    ('concentração industrial', 'concentração-industrial'),
    ('condições atmosféricas', 'condições-atmosféricas'),
    ('condições de vida', 'condições-de-vida'),
    ('condições físicas', 'condições-físicas'),
    ('condições urbanas', 'condições-urbanas'),
    ('conectividade', 'conectividade'),
    ('conferências ambientais', 'conferências-ambientais'),
    ('configuração espacial', 'configuração-espacial'),
    ('confinamento', 'confinamento'),
    ('conflito', 'conflito'),
    ('conflito armado', 'conflito-armado'),
    ('conflito indireto', 'conflito-indireto'),
    ('conflito palestino-israelense', 'conflito-palestino-israelense'),
    ('conflito regional', 'conflito-regional'),
    ('conflito árabe-israelense', 'conflito-árabe-israelense'),
    ('conflito étnico', 'conflito-étnico'),
    ('conflitos agrários', 'conflitos-agrários'),
    ('conflitos comerciais', 'conflitos-comerciais'),
    ('conflitos espaciais', 'conflitos-espaciais'),
    ('conflitos fundiários', 'conflitos-fundiários'),
    ('conflitos internacionais', 'conflitos-internacionais'),
    ('conflitos regionais', 'conflitos-regionais'),
    ('conflitos étnicos', 'conflitos-étnicos'),
    ('conformação urbana', 'conformação-urbana'),
    ('conglomerados', 'conglomerados'),
    ('consequências econômicas', 'consequências-econômicas'),
    ('consequências regionais', 'consequências-regionais'),
    ('consequências socioeconômicas', 'consequências-socioeconômicas'),
    ('consequências socioespaciais', 'consequências-socioespaciais'),
    ('conservação do solo', 'conservação-do-solo'),
    ('consumo', 'consumo'),
    ('consumo consciente', 'consumo-consciente'),
    ('consumo de energia', 'consumo-de-energia'),
    ('consumo de energia elétrica', 'consumo-de-energia-elétrica'),
    ('consumo de água', 'consumo-de-água'),
    ('contemporaneidade', 'contemporaneidade'),
    ('continentalidade', 'continentalidade'),
    ('continente africano', 'continente-africano'),
    ('continentes', 'continentes'),
    ('contradições', 'contradições'),
    ('contradições econômicas', 'contradições-econômicas'),
    ('contrastes regionais', 'contrastes-regionais'),
    ('controle da natalidade', 'controle-da-natalidade'),
    ('contágio econômico', 'contágio-econômico'),
    ('contêinerização', 'contêinerização'),
    ('conurbação', 'conurbação'),
    ('convergência e divergência', 'convergência-e-divergência'),
    ('coordenadas geográficas', 'coordenadas-geográficas'),
    ('cordilheira dos andes', 'cordilheira-dos-andes'),
    ('cordilheiras', 'cordilheiras'),
    ('coreia', 'coreia'),
    ('coreia do norte', 'coreia-do-norte'),
    ('corredores de exportação', 'corredores-de-exportação'),
    ('correlação', 'correlação'),
    ('correntes marítimas', 'correntes-marítimas'),
    ('corrida armamentista', 'corrida-armamentista'),
    ('crescimento', 'crescimento'),
    ('crescimento das cidades', 'crescimento-das-cidades'),
    ('crescimento demográfico', 'crescimento-demográfico'),
    ('crescimento econômico', 'crescimento-econômico'),
    ('crescimento populacional', 'crescimento-populacional'),
    ('crescimento urbano', 'crescimento-urbano'),
    ('crescimento vegetativo', 'crescimento-vegetativo'),
    ('criação de israel', 'criação-de-israel'),
    ('crimeia', 'crimeia'),
    ('crise', 'crise'),
    ('crise econômica', 'crise-econômica'),
    ('crise financeira', 'crise-financeira'),
    ('crise humanitária', 'crise-humanitária'),
    ('crise hídrica', 'crise-hídrica'),
    ('crise política', 'crise-política'),
    ('critérios', 'critérios'),
    ('critérios de regionalização', 'critérios-de-regionalização'),
    ('critérios geográficos', 'critérios-geográficos'),
    ('crosta terrestre', 'crosta-terrestre'),
    ('crátons', 'crátons'),
    ('crítica ao sistema financeiro', 'crítica-ao-sistema-financeiro'),
    ('cuba', 'cuba'),
    ('cultura', 'cultura'),
    ('cultura do trabalho', 'cultura-do-trabalho'),
    ('cultura indígena', 'cultura-indígena'),
    ('cultura árabe', 'cultura-árabe'),
    ('curdos', 'curdos'),
    ('custos de transporte', 'custos-de-transporte'),
    ('cálculo de escala', 'cálculo-de-escala'),
    ('cálculo de horário', 'cálculo-de-horário'),
    ('câmbio', 'câmbio'),
    ('dados', 'dados'),
    ('dados industriais', 'dados-industriais'),
    ('dados meteorológicos', 'dados-meteorológicos'),
    ('dados populacionais', 'dados-populacionais'),
    ('dados urbanos', 'dados-urbanos'),
    ('data centers', 'data-centers'),
    ('david harvey', 'david-harvey'),
    ('debate energético', 'debate-energético'),
    ('declaração universal', 'declaração-universal'),
    ('dedicação profissional', 'dedicação-profissional'),
    ('definição', 'definição'),
    ('definição agrária', 'definição-agrária'),
    ('definição territorial', 'definição-territorial'),
    ('degradação ambiental', 'degradação-ambiental'),
    ('degradação do solo', 'degradação-do-solo'),
    ('degradação florestal', 'degradação-florestal'),
    ('delta', 'delta'),
    ('demanda mundial', 'demanda-mundial'),
    ('democracia', 'democracia'),
    ('demografia', 'demografia'),
    ('demografia africana', 'demografia-africana'),
    ('demografia brasileira', 'demografia-brasileira'),
    ('deng xiaoping', 'deng-xiaoping'),
    ('densidade demográfica', 'densidade-demográfica'),
    ('dependência econômica', 'dependência-econômica'),
    ('dependência rodoviarista', 'dependência-rodoviarista'),
    ('deriva continental', 'deriva-continental'),
    ('derrames basálticos', 'derrames-basálticos'),
    ('desafios', 'desafios'),
    ('desafios da mineração', 'desafios-da-mineração'),
    ('desastre ambiental', 'desastre-ambiental'),
    ('desastres ambientais', 'desastres-ambientais'),
    ('descolonização', 'descolonização'),
    ('desconcentração', 'desconcentração'),
    ('desconcentração industrial', 'desconcentração-industrial'),
    ('descrição geográfica', 'descrição-geográfica'),
    ('desenvolvimento', 'desenvolvimento'),
    ('desenvolvimento desigual', 'desenvolvimento-desigual'),
    ('desenvolvimento econômico', 'desenvolvimento-econômico'),
    ('desenvolvimento humano', 'desenvolvimento-humano'),
    ('desenvolvimento industrial', 'desenvolvimento-industrial'),
    ('desenvolvimento regional', 'desenvolvimento-regional'),
    ('desenvolvimento sustentável', 'desenvolvimento-sustentável'),
    ('desertificação', 'desertificação'),
    ('deserto do saara', 'deserto-do-saara'),
    ('desigualdade', 'desigualdade'),
    ('desigualdade de gênero', 'desigualdade-de-gênero'),
    ('desigualdade de renda', 'desigualdade-de-renda'),
    ('desigualdade global', 'desigualdade-global'),
    ('desigualdade racial', 'desigualdade-racial'),
    ('desigualdade regional', 'desigualdade-regional'),
    ('desigualdade social', 'desigualdade-social'),
    ('desigualdade urbana', 'desigualdade-urbana'),
    ('desindustrialização', 'desindustrialização'),
    ('desintegração nacional', 'desintegração-nacional'),
    ('deslocamento forçado', 'deslocamento-forçado'),
    ('deslocamento populacional', 'deslocamento-populacional'),
    ('desmatamento', 'desmatamento'),
    ('desperdício alimentar', 'desperdício-alimentar'),
    ('desregulamentação', 'desregulamentação'),
    ('detalhamento cartográfico', 'detalhamento-cartográfico'),
    ('detroit', 'detroit'),
    ('dia mundial da água', 'dia-mundial-da-água'),
    ('diagrama', 'diagrama'),
    ('diferenças agrícolas', 'diferenças-agrícolas'),
    ('dimensões continentais', 'dimensões-continentais'),
    ('dimensões culturais', 'dimensões-culturais'),
    ('dinâmica atmosférica', 'dinâmica-atmosférica'),
    ('dinâmica climática', 'dinâmica-climática'),
    ('dinâmica fluvial', 'dinâmica-fluvial'),
    ('dinâmica terrestre', 'dinâmica-terrestre'),
    ('dinâmica urbana', 'dinâmica-urbana'),
    ('diplomacia', 'diplomacia'),
    ('direitos humanos', 'direitos-humanos'),
    ('dispersão espacial', 'dispersão-espacial'),
    ('disputa territorial', 'disputa-territorial'),
    ('distorções cartográficas', 'distorções-cartográficas'),
    ('distribuição da água', 'distribuição-da-água'),
    ('distribuição de renda', 'distribuição-de-renda'),
    ('distribuição dos biomas', 'distribuição-dos-biomas'),
    ('distribuição dos climas', 'distribuição-dos-climas'),
    ('distribuição econômica', 'distribuição-econômica'),
    ('distribuição espacial', 'distribuição-espacial'),
    ('distribuição geográfica', 'distribuição-geográfica'),
    ('distribuição industrial', 'distribuição-industrial'),
    ('distribuição populacional', 'distribuição-populacional'),
    ('distribuição regional', 'distribuição-regional'),
    ('distribuição setorial', 'distribuição-setorial'),
    ('diversidade', 'diversidade'),
    ('diversidade agrária', 'diversidade-agrária'),
    ('diversidade brasileira', 'diversidade-brasileira'),
    ('diversidade climática', 'diversidade-climática'),
    ('diversidade cultural', 'diversidade-cultural'),
    ('diversidade fisiográfica', 'diversidade-fisiográfica'),
    ('diversidade regional', 'diversidade-regional'),
    ('diversidade étnica', 'diversidade-étnica'),
    ('diversificação econômica', 'diversificação-econômica'),
    ('divisores de água', 'divisores-de-água'),
    ('divisão climática', 'divisão-climática'),
    ('divisão continental', 'divisão-continental'),
    ('divisão do trabalho', 'divisão-do-trabalho'),
    ('divisão geopolítica', 'divisão-geopolítica'),
    ('divisão internacional do trabalho', 'divisão-internacional-do-trabalho'),
    ('divisão regional', 'divisão-regional'),
    ('divisão territorial', 'divisão-territorial'),
    ('divisão territorial do trabalho', 'divisão-territorial-do-trabalho'),
    ('diáspora', 'diáspora'),
    ('dobramentos', 'dobramentos'),
    ('domínio vegetal', 'domínio-vegetal'),
    ('domínios morfoclimáticos', 'domínios-morfoclimáticos'),
    ('dorsais oceânicas', 'dorsais-oceânicas'),
    ('economia', 'economia'),
    ('economia brasileira', 'economia-brasileira'),
    ('economia canavieira', 'economia-canavieira'),
    ('economia capitalista', 'economia-capitalista'),
    ('economia colonial', 'economia-colonial'),
    ('economia de exportação', 'economia-de-exportação'),
    ('economia global', 'economia-global'),
    ('economia rural', 'economia-rural'),
    ('economias emergentes', 'economias-emergentes'),
    ('ecossistemas degradados', 'ecossistemas-degradados'),
    ('ecossistemas litorâneos', 'ecossistemas-litorâneos'),
    ('educação', 'educação'),
    ('efeito estufa', 'efeito-estufa'),
    ('eficiência energética', 'eficiência-energética'),
    ('el niño', 'el-niño'),
    ('elementos climáticos', 'elementos-climáticos'),
    ('elementos culturais', 'elementos-culturais'),
    ('elementos naturais', 'elementos-naturais'),
    ('embargo econômico', 'embargo-econômico'),
    ('emigração', 'emigração'),
    ('emissão de co2', 'emissão-de-co2'),
    ('emprego', 'emprego'),
    ('emprego formal', 'emprego-formal'),
    ('empresa estatal', 'empresa-estatal'),
    ('empresas transnacionais', 'empresas-transnacionais'),
    ('enchentes', 'enchentes'),
    ('energia', 'energia'),
    ('energia dos alimentos', 'energia-dos-alimentos'),
    ('energia elétrica', 'energia-elétrica'),
    ('energia eólica', 'energia-eólica'),
    ('energia fóssil', 'energia-fóssil'),
    ('energia hidrelétrica', 'energia-hidrelétrica'),
    ('energia nuclear', 'energia-nuclear'),
    ('energia não renovável', 'energia-não-renovável'),
    ('energia renovável', 'energia-renovável'),
    ('energia solar', 'energia-solar'),
    ('energias renováveis', 'energias-renováveis'),
    ('engenharia', 'engenharia'),
    ('envelhecimento', 'envelhecimento'),
    ('envelhecimento global', 'envelhecimento-global'),
    ('envelhecimento populacional', 'envelhecimento-populacional'),
    ('eras geológicas', 'eras-geológicas'),
    ('erosão', 'erosão'),
    ('erosão fluvial', 'erosão-fluvial'),
    ('erosão glacial', 'erosão-glacial'),
    ('erosão marinha', 'erosão-marinha'),
    ('erupção vulcânica', 'erupção-vulcânica'),
    ('escala cartográfica', 'escala-cartográfica'),
    ('escala geográfica', 'escala-geográfica'),
    ('escala gráfica', 'escala-gráfica'),
    ('escala numérica', 'escala-numérica'),
    ('escarpas', 'escarpas'),
    ('escassez de água', 'escassez-de-água'),
    ('escassez hídrica', 'escassez-hídrica'),
    ('escudos cristalinos', 'escudos-cristalinos'),
    ('espacialidades', 'espacialidades'),
    ('espanha', 'espanha'),
    ('espaço agrário', 'espaço-agrário'),
    ('espaço econômico', 'espaço-econômico'),
    ('espaço geográfico', 'espaço-geográfico'),
    ('espaço global', 'espaço-global'),
    ('espaço industrial', 'espaço-industrial'),
    ('espaço mundial', 'espaço-mundial'),
    ('espaço rural', 'espaço-rural'),
    ('espaço urbano', 'espaço-urbano'),
    ('especulação', 'especulação'),
    ('especulação imobiliária', 'especulação-imobiliária'),
    ('esporte', 'esporte'),
    ('espécies endêmicas', 'espécies-endêmicas'),
    ('esquerda', 'esquerda'),
    ('estado', 'estado'),
    ('estado islâmico', 'estado-islâmico'),
    ('estados paralelos', 'estados-paralelos'),
    ('estatuto da cidade', 'estatuto-da-cidade'),
    ('estatística social', 'estatística-social'),
    ('estações do ano', 'estações-do-ano'),
    ('estocolmo 1972', 'estocolmo-1972'),
    ('estoques', 'estoques'),
    ('estrada real', 'estrada-real'),
    ('estratégia', 'estratégia'),
    ('estratégia econômica', 'estratégia-econômica'),
    ('estrutura demográfica', 'estrutura-demográfica'),
    ('estrutura econômica', 'estrutura-econômica'),
    ('estrutura etária', 'estrutura-etária'),
    ('estrutura fundiária', 'estrutura-fundiária'),
    ('estrutura geológica', 'estrutura-geológica'),
    ('estrutura interna da terra', 'estrutura-interna-da-terra'),
    ('estrutura interna das cidades', 'estrutura-interna-das-cidades'),
    ('estrutura ocupacional', 'estrutura-ocupacional'),
    ('estrutura populacional', 'estrutura-populacional'),
    ('estrutura étnica', 'estrutura-étnica'),
    ('estruturas geológicas', 'estruturas-geológicas'),
    ('etanol', 'etanol'),
    ('etapas da industrialização', 'etapas-da-industrialização'),
    ('etiópia', 'etiópia'),
    ('etnias', 'etnias'),
    ('eua', 'eua'),
    ('europa', 'europa'),
    ('evaporação', 'evaporação'),
    ('eventos esportivos', 'eventos-esportivos'),
    ('evo morales', 'evo-morales'),
    ('expansionismo', 'expansionismo'),
    ('expansão', 'expansão'),
    ('expansão agrícola', 'expansão-agrícola'),
    ('expansão canavieira', 'expansão-canavieira'),
    ('expansão da fronteira agrícola', 'expansão-da-fronteira-agrícola'),
    ('expansão das redes', 'expansão-das-redes'),
    ('expansão do fundo oceânico', 'expansão-do-fundo-oceânico'),
    ('expansão do território', 'expansão-do-território'),
    ('expansão energética', 'expansão-energética'),
    ('expansão territorial', 'expansão-territorial'),
    ('expansão urbana', 'expansão-urbana'),
    ('expectativa de vida', 'expectativa-de-vida'),
    ('exploração', 'exploração'),
    ('exportação', 'exportação'),
    ('exportação de grãos', 'exportação-de-grãos'),
    ('exportação mineral', 'exportação-mineral'),
    ('exportações', 'exportações'),
    ('exportações brasileiras', 'exportações-brasileiras'),
    ('extrativismo vegetal', 'extrativismo-vegetal'),
    ('extração mineral', 'extração-mineral'),
    ('extrema-direita', 'extrema-direita'),
    ('extremismo religioso', 'extremismo-religioso'),
    ('faixas climáticas', 'faixas-climáticas'),
    ('fao', 'fao'),
    ('farc', 'farc'),
    ('fases do capitalismo', 'fases-do-capitalismo'),
    ('fator geográfico', 'fator-geográfico'),
    ('fatores climáticos', 'fatores-climáticos'),
    ('fatores de produção', 'fatores-de-produção'),
    ('fatores locacionais', 'fatores-locacionais'),
    ('favelas', 'favelas'),
    ('favelização', 'favelização'),
    ('fecundidade', 'fecundidade'),
    ('fenômenos astronômicos', 'fenômenos-astronômicos'),
    ('fenômenos climáticos', 'fenômenos-climáticos'),
    ('ferrovia transiberiana', 'ferrovia-transiberiana'),
    ('fim da união soviética', 'fim-da-união-soviética'),
    ('fim do socialismo', 'fim-do-socialismo'),
    ('financeirização', 'financeirização'),
    ('fiscalização ambiental', 'fiscalização-ambiental'),
    ('fitomassa', 'fitomassa'),
    ('floresta amazônica', 'floresta-amazônica'),
    ('floresta boreal', 'floresta-boreal'),
    ('floresta tropical', 'floresta-tropical'),
    ('fluxo migratório', 'fluxo-migratório'),
    ('fluxos', 'fluxos'),
    ('fluxos digitais', 'fluxos-digitais'),
    ('fluxos globais', 'fluxos-globais'),
    ('fluxos imateriais', 'fluxos-imateriais'),
    ('fluxos migratórios', 'fluxos-migratórios'),
    ('fluxos migratórios internacionais', 'fluxos-migratórios-internacionais'),
    ('fluxos populacionais', 'fluxos-populacionais'),
    ('fmi', 'fmi'),
    ('fome', 'fome'),
    ('fontes alternativas', 'fontes-alternativas'),
    ('fontes alternativas de energia', 'fontes-alternativas-de-energia'),
    ('fontes de energia', 'fontes-de-energia'),
    ('fontes renováveis', 'fontes-renováveis'),
    ('ford', 'ford'),
    ('fordismo', 'fordismo'),
    ('forma de ocupação produtiva', 'forma-de-ocupação-produtiva'),
    ('formas de relevo', 'formas-de-relevo'),
    ('formas visíveis e invisíveis', 'formas-visíveis-e-invisíveis'),
    ('formação cultural', 'formação-cultural'),
    ('formação do relevo', 'formação-do-relevo'),
    ('formação do solo', 'formação-do-solo'),
    ('formação dos continentes', 'formação-dos-continentes'),
    ('formação territorial', 'formação-territorial'),
    ('formação étnica', 'formação-étnica'),
    ('formações vegetais', 'formações-vegetais'),
    ('fragmentação', 'fragmentação'),
    ('fragmentação florestal', 'fragmentação-florestal'),
    ('fragmentação territorial', 'fragmentação-territorial'),
    ('francofonia', 'francofonia'),
    ('frente fria', 'frente-fria'),
    ('frentes', 'frentes'),
    ('frentes de expansão', 'frentes-de-expansão'),
    ('frentes frias', 'frentes-frias'),
    ('friagem amazônica', 'friagem-amazônica'),
    ('fronteira', 'fronteira'),
    ('fronteira agrícola', 'fronteira-agrícola'),
    ('fronteiras africanas', 'fronteiras-africanas'),
    ('fronteiras brasileiras', 'fronteiras-brasileiras'),
    ('fundamentalismo', 'fundamentalismo'),
    ('função social da cidade', 'função-social-da-cidade'),
    ('função social da terra', 'função-social-da-terra'),
    ('fuso horário', 'fuso-horário'),
    ('fusos horários', 'fusos-horários'),
    ('fusão de cidades', 'fusão-de-cidades'),
    ('fósseis', 'fósseis'),
    ('gabriel boric', 'gabriel-boric'),
    ('gases de efeito estufa', 'gases-de-efeito-estufa'),
    ('gasoduto', 'gasoduto'),
    ('gasto militar', 'gasto-militar'),
    ('geiger', 'geiger'),
    ('geleiras', 'geleiras'),
    ('generalização cartográfica', 'generalização-cartográfica'),
    ('genocídio', 'genocídio'),
    ('gentrificação', 'gentrificação'),
    ('geoeconômica', 'geoeconômica'),
    ('geografia', 'geografia'),
    ('geografia física', 'geografia-física'),
    ('geografia humana', 'geografia-humana'),
    ('geologia', 'geologia'),
    ('geologia brasileira', 'geologia-brasileira'),
    ('geologia e mineração', 'geologia-e-mineração'),
    ('geomorfologia', 'geomorfologia'),
    ('geomorfologia fluvial', 'geomorfologia-fluvial'),
    ('geopolítica', 'geopolítica'),
    ('geopolítica do petróleo', 'geopolítica-do-petróleo'),
    ('geopolítica europeia', 'geopolítica-europeia'),
    ('geopolítica tecnológica', 'geopolítica-tecnológica'),
    ('geoprocessamento', 'geoprocessamento'),
    ('geotecnologias', 'geotecnologias'),
    ('geração de energia', 'geração-de-energia'),
    ('geração de energia elétrica', 'geração-de-energia-elétrica'),
    ('gerenciamento hídrico', 'gerenciamento-hídrico'),
    ('gestão das águas', 'gestão-das-águas'),
    ('gestão de recursos hídricos', 'gestão-de-recursos-hídricos'),
    ('gestão de resíduos', 'gestão-de-resíduos'),
    ('glaciologia', 'glaciologia'),
    ('globalização', 'globalização'),
    ('globalização financeira', 'globalização-financeira'),
    ('golpe de estado', 'golpe-de-estado'),
    ('golpes de estado', 'golpes-de-estado'),
    ('gps', 'gps'),
    ('grilagem', 'grilagem'),
    ('gráfico demográfico', 'gráfico-demográfico'),
    ('guerra', 'guerra'),
    ('guerra civil', 'guerra-civil'),
    ('guerra do golfo', 'guerra-do-golfo'),
    ('guerra fria', 'guerra-fria'),
    ('guerras contemporâneas', 'guerras-contemporâneas'),
    ('guerrilha', 'guerrilha'),
    ('gás natural', 'gás-natural'),
    ('gênero', 'gênero'),
    ('habitação', 'habitação'),
    ('habitação popular', 'habitação-popular'),
    ('haiti', 'haiti'),
    ('hegemonia', 'hegemonia'),
    ('hemisfério', 'hemisfério'),
    ('herança colonial', 'herança-colonial'),
    ('herbicida', 'herbicida'),
    ('hidrelétrica', 'hidrelétrica'),
    ('hidrelétricas brasileiras', 'hidrelétricas-brasileiras'),
    ('hidrografia', 'hidrografia'),
    ('hidrografia brasileira', 'hidrografia-brasileira'),
    ('hidrologia', 'hidrologia'),
    ('hidrovia', 'hidrovia'),
    ('hierarquia das cidades', 'hierarquia-das-cidades'),
    ('hierarquia urbana', 'hierarquia-urbana'),
    ('hispânicos', 'hispânicos'),
    ('história', 'história'),
    ('história colonial', 'história-colonial'),
    ('história da geografia', 'história-da-geografia'),
    ('história da integração', 'história-da-integração'),
    ('história da integração europeia', 'história-da-integração-europeia'),
    ('história econômica', 'história-econômica'),
    ('história industrial', 'história-industrial'),
    ('histórico', 'histórico'),
    ('homogeneização', 'homogeneização'),
    ('hong kong', 'hong-kong'),
    ('horizonte do solo', 'horizonte-do-solo'),
    ('horta urbana', 'horta-urbana'),
    ('hugo chávez', 'hugo-chávez'),
    ('ibama', 'ibama'),
    ('ibge', 'ibge'),
    ('iceberg', 'iceberg'),
    ('identidade', 'identidade'),
    ('identidade brasileira', 'identidade-brasileira'),
    ('identidade europeia', 'identidade-europeia'),
    ('identidade regional', 'identidade-regional'),
    ('identificação de bioma', 'identificação-de-bioma'),
    ('idh', 'idh'),
    ('idh-m', 'idh-m'),
    ('iirsa', 'iirsa'),
    ('ilha de calor', 'ilha-de-calor'),
    ('ilha de calor urbana', 'ilha-de-calor-urbana'),
    ('ilhas', 'ilhas'),
    ('imagens de satélite', 'imagens-de-satélite'),
    ('imigração', 'imigração'),
    ('imigração europeia', 'imigração-europeia'),
    ('imigração mexicana', 'imigração-mexicana'),
    ('impacto ambiental', 'impacto-ambiental'),
    ('impacto humano', 'impacto-humano'),
    ('impacto urbano', 'impacto-urbano'),
    ('impactos ambientais', 'impactos-ambientais'),
    ('imperialismo', 'imperialismo'),
    ('impermeabilização do solo', 'impermeabilização-do-solo'),
    ('importações', 'importações'),
    ('imóveis rurais', 'imóveis-rurais'),
    ('independência', 'independência'),
    ('indicadores', 'indicadores'),
    ('indicadores demográficos', 'indicadores-demográficos'),
    ('indicadores econômicos', 'indicadores-econômicos'),
    ('indicadores sociais', 'indicadores-sociais'),
    ('indicadores socioeconômicos', 'indicadores-socioeconômicos'),
    ('industrialização', 'industrialização'),
    ('industrialização agrícola', 'industrialização-agrícola'),
    ('industrialização brasileira', 'industrialização-brasileira'),
    ('industrialização pesada', 'industrialização-pesada'),
    ('industrialização tardia', 'industrialização-tardia'),
    ('indústria', 'indústria'),
    ('indústria automobilística', 'indústria-automobilística'),
    ('indústria automotiva', 'indústria-automotiva'),
    ('indústria brasileira', 'indústria-brasileira'),
    ('influência oceânica no clima', 'influência-oceânica-no-clima'),
    ('informação', 'informação'),
    ('infraestrutura', 'infraestrutura'),
    ('infraestrutura de transportes', 'infraestrutura-de-transportes'),
    ('infraestrutura digital', 'infraestrutura-digital'),
    ('infraestrutura urbana', 'infraestrutura-urbana'),
    ('inovação', 'inovação'),
    ('instabilidade', 'instabilidade'),
    ('instabilidade atmosférica', 'instabilidade-atmosférica'),
    ('instabilidade política', 'instabilidade-política'),
    ('instituições financeiras', 'instituições-financeiras'),
    ('integração', 'integração'),
    ('integração econômica', 'integração-econômica'),
    ('integração energética', 'integração-energética'),
    ('integração global', 'integração-global'),
    ('integração nacional', 'integração-nacional'),
    ('integração regional', 'integração-regional'),
    ('integração sul-americana', 'integração-sul-americana'),
    ('integração territorial', 'integração-territorial'),
    ('intemperismo', 'intemperismo'),
    ('interação sociedade-natureza', 'interação-sociedade-natureza'),
    ('interior paulista', 'interior-paulista'),
    ('intermodalidade', 'intermodalidade'),
    ('internet', 'internet'),
    ('intervenção militar', 'intervenção-militar'),
    ('inundações sazonais', 'inundações-sazonais'),
    ('invasão', 'invasão'),
    ('invasão dos aliados', 'invasão-dos-aliados'),
    ('invenção cultural', 'invenção-cultural'),
    ('inversão térmica', 'inversão-térmica'),
    ('investimento estrangeiro', 'investimento-estrangeiro'),
    ('iraque', 'iraque'),
    ('irradiação territorial', 'irradiação-territorial'),
    ('irã', 'irã'),
    ('isis', 'isis'),
    ('islamismo', 'islamismo'),
    ('isolamento', 'isolamento'),
    ('israel', 'israel'),
    ('istmo', 'istmo'),
    ('itaipu', 'itaipu'),
    ('japão', 'japão'),
    ('jk', 'jk'),
    ('jovens', 'jovens'),
    ('just-in-time', 'just-in-time'),
    ('karoshi', 'karoshi'),
    ('karst', 'karst'),
    ('kurdistan', 'kurdistan'),
    ('la niña', 'la-niña'),
    ('latifúndio', 'latifúndio'),
    ('latitude', 'latitude'),
    ('legislação', 'legislação'),
    ('legislação ambiental', 'legislação-ambiental'),
    ('lei das águas', 'lei-das-águas'),
    ('lei de segurança', 'lei-de-segurança'),
    ('lei do biodiesel', 'lei-do-biodiesel'),
    ('limites geográficos', 'limites-geográficos'),
    ('linguística', 'linguística'),
    ('linha internacional de mudança de data', 'linha-internacional-de-mudança-de-data'),
    ('litoral', 'litoral'),
    ('litoral brasileiro', 'litoral-brasileiro'),
    ('litoral colonial', 'litoral-colonial'),
    ('litoral nordestino', 'litoral-nordestino'),
    ('litosfera', 'litosfera'),
    ('livre-comércio', 'livre-comércio'),
    ('livre-mercado', 'livre-mercado'),
    ('lixão', 'lixão'),
    ('localismo', 'localismo'),
    ('localização', 'localização'),
    ('localização de usinas', 'localização-de-usinas'),
    ('localização geográfica', 'localização-geográfica'),
    ('localização histórica', 'localização-histórica'),
    ('localização industrial', 'localização-industrial'),
    ('logística', 'logística'),
    ('logística brasileira', 'logística-brasileira'),
    ('longevidade', 'longevidade'),
    ('longitude', 'longitude'),
    ('lugar', 'lugar'),
    ('luta pela terra', 'luta-pela-terra'),
    ('lúcio costa', 'lúcio-costa'),
    ('magma', 'magma'),
    ('maiores concentrações urbanas', 'maiores-concentrações-urbanas'),
    ('malthusianismo', 'malthusianismo'),
    ('manchete de jornal', 'manchete-de-jornal'),
    ('manejo do fogo', 'manejo-do-fogo'),
    ('manguezal', 'manguezal'),
    ('mapa', 'mapa'),
    ('mapa climático', 'mapa-climático'),
    ('mapa de biomas', 'mapa-de-biomas'),
    ('mapa de migração', 'mapa-de-migração'),
    ('mapa de recursos minerais', 'mapa-de-recursos-minerais'),
    ('mapa demográfico', 'mapa-demográfico'),
    ('mapa geológico', 'mapa-geológico'),
    ('mapa industrial', 'mapa-industrial'),
    ('mapa regional', 'mapa-regional'),
    ('mapa urbano', 'mapa-urbano'),
    ('mapas do brasil', 'mapas-do-brasil'),
    ('mapas temáticos', 'mapas-temáticos'),
    ('mapeamento', 'mapeamento'),
    ('mar de aral', 'mar-de-aral'),
    ('mar do sul', 'mar-do-sul'),
    ('marginalização econômica', 'marginalização-econômica'),
    ('massa polar', 'massa-polar'),
    ('massas de ar', 'massas-de-ar'),
    ('massas de ar brasileiras', 'massas-de-ar-brasileiras'),
    ('mata atlântica', 'mata-atlântica'),
    ('mata de araucária', 'mata-de-araucária'),
    ('materialidade', 'materialidade'),
    ('matriz de transporte', 'matriz-de-transporte'),
    ('matriz energética', 'matriz-energética'),
    ('matriz energética brasileira', 'matriz-energética-brasileira'),
    ('matéria-prima agrícola', 'matéria-prima-agrícola'),
    ('meandro', 'meandro'),
    ('mecanização', 'mecanização'),
    ('megacidades', 'megacidades'),
    ('meio ambiente', 'meio-ambiente'),
    ('meio técnico-científico', 'meio-técnico-científico'),
    ('meio técnico-científico-informacional', 'meio-técnico-científico-informacional'),
    ('memes', 'memes'),
    ('mensuração econômica', 'mensuração-econômica'),
    ('mercado', 'mercado'),
    ('mercado de trabalho', 'mercado-de-trabalho'),
    ('mercado financeiro', 'mercado-financeiro'),
    ('mercado global', 'mercado-global'),
    ('mercado mundial', 'mercado-mundial'),
    ('mercosul', 'mercosul'),
    ('meridiano de greenwich', 'meridiano-de-greenwich'),
    ('meridianos', 'meridianos'),
    ('mesopotâmia', 'mesopotâmia'),
    ('mestiçagem', 'mestiçagem'),
    ('metabolismo humano', 'metabolismo-humano'),
    ('metais', 'metais'),
    ('meteorologia', 'meteorologia'),
    ('metropolização', 'metropolização'),
    ('metrópole', 'metrópole'),
    ('metrópole contemporânea', 'metrópole-contemporânea'),
    ('metrópoles brasileiras', 'metrópoles-brasileiras'),
    ('mianmar', 'mianmar'),
    ('migrantes', 'migrantes'),
    ('migração', 'migração'),
    ('migração campo-cidade', 'migração-campo-cidade'),
    ('migração e urbanização', 'migração-e-urbanização'),
    ('migração econômica', 'migração-econômica'),
    ('migração global', 'migração-global'),
    ('migração internacional', 'migração-internacional'),
    ('migração laboral', 'migração-laboral'),
    ('migração sazonal', 'migração-sazonal'),
    ('migrações brasileiras', 'migrações-brasileiras'),
    ('migrações internas', 'migrações-internas'),
    ('milagre econômico', 'milagre-econômico'),
    ('milagre japonês', 'milagre-japonês'),
    ('milho', 'milho'),
    ('milton santos', 'milton-santos'),
    ('minerais', 'minerais'),
    ('mineração', 'mineração'),
    ('mineração brasileira', 'mineração-brasileira'),
    ('mineração colonial', 'mineração-colonial'),
    ('minoria étnica', 'minoria-étnica'),
    ('minorias', 'minorias'),
    ('miscigenação', 'miscigenação'),
    ('mobilidade populacional', 'mobilidade-populacional'),
    ('modal de transporte', 'modal-de-transporte'),
    ('modelo econômico', 'modelo-econômico'),
    ('modelo híbrido', 'modelo-híbrido'),
    ('modelo industrial', 'modelo-industrial'),
    ('modernidade', 'modernidade'),
    ('modernização', 'modernização'),
    ('modernização agrícola', 'modernização-agrícola'),
    ('modernização industrial', 'modernização-industrial'),
    ('modificações ambientais', 'modificações-ambientais'),
    ('monocultura', 'monocultura'),
    ('montanhas', 'montanhas'),
    ('moralidade econômica', 'moralidade-econômica'),
    ('mortalidade', 'mortalidade'),
    ('mortalidade infantil', 'mortalidade-infantil'),
    ('movimento do ar', 'movimento-do-ar'),
    ('movimento independentista', 'movimento-independentista'),
    ('movimentos ambientalistas', 'movimentos-ambientalistas'),
    ('movimentos armados', 'movimentos-armados'),
    ('movimentos das placas', 'movimentos-das-placas'),
    ('movimentos de massa', 'movimentos-de-massa'),
    ('movimentos sociais', 'movimentos-sociais'),
    ('mst', 'mst'),
    ('mudanças climáticas', 'mudanças-climáticas'),
    ('multinacionais', 'multinacionais'),
    ('multipolaridade', 'multipolaridade'),
    ('mundo do trabalho', 'mundo-do-trabalho'),
    ('municípios', 'municípios'),
    ('municípios brasileiros', 'municípios-brasileiros'),
    ('muro de berlim', 'muro-de-berlim'),
    ('máquina a vapor', 'máquina-a-vapor'),
    ('méxico', 'méxico'),
    ('nafta', 'nafta'),
    ('nascentes', 'nascentes'),
    ('natalidade', 'natalidade'),
    ('natureza', 'natureza'),
    ('natureza e sociedade', 'natureza-e-sociedade'),
    ('nação', 'nação'),
    ('neocolonialismo', 'neocolonialismo'),
    ('neoliberalismo', 'neoliberalismo'),
    ('neve no brasil', 'neve-no-brasil'),
    ('nigéria', 'nigéria'),
    ('nordeste', 'nordeste'),
    ('normas ambientais', 'normas-ambientais'),
    ('nova ordem mundial', 'nova-ordem-mundial'),
    ('nova zelândia', 'nova-zelândia'),
    ('novos tigres asiáticos', 'novos-tigres-asiáticos'),
    ('nível de integração', 'nível-de-integração'),
    ('núcleo', 'núcleo'),
    ('objetivos', 'objetivos'),
    ('objetivos econômicos', 'objetivos-econômicos'),
    ('objeto de estudo da geografia', 'objeto-de-estudo-da-geografia'),
    ('obstáculos fundiários', 'obstáculos-fundiários'),
    ('oceania', 'oceania'),
    ('oceanos', 'oceanos'),
    ('ocidente', 'ocidente'),
    ('ocupação', 'ocupação'),
    ('ocupação da terra', 'ocupação-da-terra'),
    ('ocupação do território', 'ocupação-do-território'),
    ('oit', 'oit'),
    ('oligopólio', 'oligopólio'),
    ('olimpíadas', 'olimpíadas'),
    ('omc', 'omc'),
    ('onu', 'onu'),
    ('ordem mundial', 'ordem-mundial'),
    ('organização do espaço', 'organização-do-espaço'),
    ('organização do trabalho', 'organização-do-trabalho'),
    ('organização interna urbana', 'organização-interna-urbana'),
    ('organização internacional', 'organização-internacional'),
    ('organização regional', 'organização-regional'),
    ('orientação', 'orientação'),
    ('oriente médio', 'oriente-médio'),
    ('origem', 'origem'),
    ('otan', 'otan'),
    ('ouro', 'ouro'),
    ('paisagem', 'paisagem'),
    ('paisagens naturais', 'paisagens-naturais'),
    ('palestina', 'palestina'),
    ('pampa', 'pampa'),
    ('pangeia', 'pangeia'),
    ('pantanal', 'pantanal'),
    ('papel geopolítico', 'papel-geopolítico'),
    ('paquistão', 'paquistão'),
    ('paraguai', 'paraguai'),
    ('paralelos', 'paralelos'),
    ('paraná', 'paraná'),
    ('parque industrial', 'parque-industrial'),
    ('pastagem', 'pastagem'),
    ('patrimônio cultural', 'patrimônio-cultural'),
    ('pauta de exportações', 'pauta-de-exportações'),
    ('país basco', 'país-basco'),
    ('países', 'países'),
    ('países africanos', 'países-africanos'),
    ('países andinos', 'países-andinos'),
    ('países desenvolvidos', 'países-desenvolvidos'),
    ('países em desenvolvimento', 'países-em-desenvolvimento'),
    ('países emergentes', 'países-emergentes'),
    ('países islâmicos', 'países-islâmicos'),
    ('países membros', 'países-membros'),
    ('países periféricos', 'países-periféricos'),
    ('países pobres e ricos', 'países-pobres-e-ricos'),
    ('países subdesenvolvidos', 'países-subdesenvolvidos'),
    ('países-polo', 'países-polo'),
    ('pea', 'pea'),
    ('pea feminina', 'pea-feminina'),
    ('pecuária', 'pecuária'),
    ('pecuária intensiva', 'pecuária-intensiva'),
    ('pedologia', 'pedologia'),
    ('perfil natural', 'perfil-natural'),
    ('perfil natural e socioeconômico', 'perfil-natural-e-socioeconômico'),
    ('perfil socioeconômico', 'perfil-socioeconômico'),
    ('periferização', 'periferização'),
    ('perseguição étnica', 'perseguição-étnica'),
    ('período colonial', 'período-colonial'),
    ('petrobras', 'petrobras'),
    ('petróleo', 'petróleo'),
    ('petróleo brasileiro', 'petróleo-brasileiro'),
    ('ph', 'ph'),
    ('pib', 'pib'),
    ('pirâmide etária', 'pirâmide-etária'),
    ('pkk', 'pkk'),
    ('placas tectônicas', 'placas-tectônicas'),
    ('planalto central', 'planalto-central'),
    ('planaltos', 'planaltos'),
    ('planaltos e planícies', 'planaltos-e-planícies'),
    ('planejamento econômico', 'planejamento-econômico'),
    ('planejamento regional', 'planejamento-regional'),
    ('planejamento urbano', 'planejamento-urbano'),
    ('plantation', 'plantation'),
    ('planície pantaneira', 'planície-pantaneira'),
    ('planícies', 'planícies'),
    ('plataforma continental', 'plataforma-continental'),
    ('plataforma petrolífera', 'plataforma-petrolífera'),
    ('pnuma', 'pnuma'),
    ('pobreza', 'pobreza'),
    ('poder geopolítico', 'poder-geopolítico'),
    ('poder público', 'poder-público'),
    ('polo industrial', 'polo-industrial'),
    ('polo tecnológico', 'polo-tecnológico'),
    ('poluição', 'poluição'),
    ('poluição atmosférica', 'poluição-atmosférica'),
    ('poluição das águas', 'poluição-das-águas'),
    ('poluição do ar', 'poluição-do-ar'),
    ('poluição industrial', 'poluição-industrial'),
    ('poluição urbana', 'poluição-urbana'),
    ('política', 'política'),
    ('política demográfica', 'política-demográfica'),
    ('política externa', 'política-externa'),
    ('política industrial', 'política-industrial'),
    ('política migratória', 'política-migratória'),
    ('política pública', 'política-pública'),
    ('política urbana', 'política-urbana'),
    ('políticas ambientais', 'políticas-ambientais'),
    ('políticas públicas', 'políticas-públicas'),
    ('pontos cardeais', 'pontos-cardeais'),
    ('população', 'população'),
    ('população economicamente ativa', 'população-economicamente-ativa'),
    ('população indígena', 'população-indígena'),
    ('população negra', 'população-negra'),
    ('população relativa', 'população-relativa'),
    ('população urbana', 'população-urbana'),
    ('populações', 'populações'),
    ('populações absolutas', 'populações-absolutas'),
    ('populismo', 'populismo'),
    ('porto', 'porto'),
    ('potencial mineral', 'potencial-mineral'),
    ('potência agrícola', 'potência-agrícola'),
    ('potência emergente', 'potência-emergente'),
    ('potência industrial', 'potência-industrial'),
    ('potência mundial', 'potência-mundial'),
    ('potências emergentes', 'potências-emergentes'),
    ('povo', 'povo'),
    ('povo brasileiro', 'povo-brasileiro'),
    ('povoamento do brasil', 'povoamento-do-brasil'),
    ('precipitação', 'precipitação'),
    ('preservação', 'preservação'),
    ('preservação ambiental', 'preservação-ambiental'),
    ('pressão atmosférica', 'pressão-atmosférica'),
    ('primarização da economia', 'primarização-da-economia'),
    ('primazia econômica', 'primazia-econômica'),
    ('primeira revolução industrial', 'primeira-revolução-industrial'),
    ('privatizações', 'privatizações'),
    ('problema ambiental', 'problema-ambiental'),
    ('problema central', 'problema-central'),
    ('problema socioambiental', 'problema-socioambiental'),
    ('problemas rurais', 'problemas-rurais'),
    ('problemas urbanos', 'problemas-urbanos'),
    ('processo urbano', 'processo-urbano'),
    ('processos urbanos', 'processos-urbanos'),
    ('produto interno bruto', 'produto-interno-bruto'),
    ('produtos cartográficos', 'produtos-cartográficos'),
    ('produção', 'produção'),
    ('produção agropecuária', 'produção-agropecuária'),
    ('produção agrária', 'produção-agrária'),
    ('produção agrícola', 'produção-agrícola'),
    ('produção agrícola mundial', 'produção-agrícola-mundial'),
    ('produção alimentar', 'produção-alimentar'),
    ('produção de alimentos', 'produção-de-alimentos'),
    ('produção em série', 'produção-em-série'),
    ('produção energética', 'produção-energética'),
    ('produção fabril', 'produção-fabril'),
    ('produção flexível', 'produção-flexível'),
    ('produção florestal', 'produção-florestal'),
    ('produção globalizada', 'produção-globalizada'),
    ('produção industrial', 'produção-industrial'),
    ('produção sustentável', 'produção-sustentável'),
    ('projeto ambiental', 'projeto-ambiental'),
    ('projeção de mercator', 'projeção-de-mercator'),
    ('projeção demográfica', 'projeção-demográfica'),
    ('projeções cartográficas', 'projeções-cartográficas'),
    ('projeções populacionais', 'projeções-populacionais'),
    ('proporcionalidade', 'proporcionalidade'),
    ('propriedade rural', 'propriedade-rural'),
    ('protecionismo', 'protecionismo'),
    ('protestos', 'protestos'),
    ('protocolo de kyoto', 'protocolo-de-kyoto'),
    ('províncias geológicas', 'províncias-geológicas'),
    ('prática produtiva sustentável', 'prática-produtiva-sustentável'),
    ('pré-sal', 'pré-sal'),
    ('putin', 'putin'),
    ('pós-guerra', 'pós-guerra'),
    ('pós-guerra fria', 'pós-guerra-fria'),
    ('qualidade de vida', 'qualidade-de-vida'),
    ('qualidade do ar', 'qualidade-do-ar'),
    ('quebec', 'quebec'),
    ('queimadas', 'queimadas'),
    ('questão agrária', 'questão-agrária'),
    ('questão ambiental', 'questão-ambiental'),
    ('questão ambiental urbana', 'questão-ambiental-urbana'),
    ('questão palestina', 'questão-palestina'),
    ('questões ambientais', 'questões-ambientais'),
    ('questões ambientais globais', 'questões-ambientais-globais'),
    ('questões indígenas', 'questões-indígenas'),
    ('radambrasil', 'radambrasil'),
    ('radiação solar', 'radiação-solar'),
    ('radicalismo', 'radicalismo'),
    ('rebeldes', 'rebeldes'),
    ('reciclagem', 'reciclagem'),
    ('reconfiguração territorial', 'reconfiguração-territorial'),
    ('recurso natural', 'recurso-natural'),
    ('recursos energéticos', 'recursos-energéticos'),
    ('recursos hídricos', 'recursos-hídricos'),
    ('recursos hídricos subterrâneos', 'recursos-hídricos-subterrâneos'),
    ('recursos minerais', 'recursos-minerais'),
    ('recursos naturais', 'recursos-naturais'),
    ('rede urbana', 'rede-urbana'),
    ('rede urbana brasileira', 'rede-urbana-brasileira'),
    ('rede urbana mundial', 'rede-urbana-mundial'),
    ('redes', 'redes'),
    ('redes de transporte', 'redes-de-transporte'),
    ('redes geográficas', 'redes-geográficas'),
    ('redes produtivas', 'redes-produtivas'),
    ('redes sociais', 'redes-sociais'),
    ('reestruturação', 'reestruturação'),
    ('reestruturação produtiva', 'reestruturação-produtiva'),
    ('referendo', 'referendo'),
    ('refinaria', 'refinaria'),
    ('reforma agrária', 'reforma-agrária'),
    ('refugiados', 'refugiados'),
    ('regime de chuvas', 'regime-de-chuvas'),
    ('regime político', 'regime-político'),
    ('regionalização', 'regionalização'),
    ('regionalização brasileira', 'regionalização-brasileira'),
    ('regionalização de geiger', 'regionalização-de-geiger'),
    ('regionalização do brasil', 'regionalização-do-brasil'),
    ('região asiática', 'região-asiática'),
    ('região geográfica', 'região-geográfica'),
    ('região metropolitana', 'região-metropolitana'),
    ('região sul', 'região-sul'),
    ('regiões', 'regiões'),
    ('regiões brasileiras', 'regiões-brasileiras'),
    ('regiões de origem', 'regiões-de-origem'),
    ('regiões geoeconômicas', 'regiões-geoeconômicas'),
    ('regiões hidrográficas', 'regiões-hidrográficas'),
    ('regiões ibge', 'regiões-ibge'),
    ('regiões industriais', 'regiões-industriais'),
    ('reino unido', 'reino-unido'),
    ('rejeitos radioativos', 'rejeitos-radioativos'),
    ('relação cidade-entorno', 'relação-cidade-entorno'),
    ('relações bilaterais', 'relações-bilaterais'),
    ('relações binacionais', 'relações-binacionais'),
    ('relevo', 'relevo'),
    ('relevo brasileiro', 'relevo-brasileiro'),
    ('relevo costeiro', 'relevo-costeiro'),
    ('relevo do brasil', 'relevo-do-brasil'),
    ('relevo europeu', 'relevo-europeu'),
    ('relevo submarino', 'relevo-submarino'),
    ('religião', 'religião'),
    ('remessas', 'remessas'),
    ('renda', 'renda'),
    ('renda média', 'renda-média'),
    ('renovação urbana', 'renovação-urbana'),
    ('reordenamento territorial', 'reordenamento-territorial'),
    ('representação cartográfica', 'representação-cartográfica'),
    ('república islâmica', 'república-islâmica'),
    ('reservas extrativistas', 'reservas-extrativistas'),
    ('resex', 'resex'),
    ('resolução', 'resolução'),
    ('resposta geopolítica', 'resposta-geopolítica'),
    ('restinga', 'restinga'),
    ('resíduos sólidos', 'resíduos-sólidos'),
    ('reunificação alemã', 'reunificação-alemã'),
    ('reutilização da água', 'reutilização-da-água'),
    ('revolução industrial', 'revolução-industrial'),
    ('revolução informacional', 'revolução-informacional'),
    ('revolução iraniana', 'revolução-iraniana'),
    ('revolução tecnológica', 'revolução-tecnológica'),
    ('revolução verde', 'revolução-verde'),
    ('revoluções industriais', 'revoluções-industriais'),
    ('rio amarelo', 'rio-amarelo'),
    ('rio de janeiro', 'rio-de-janeiro'),
    ('rio são lourenço', 'rio-são-lourenço'),
    ('rio+20', 'rio-20'),
    ('rios', 'rios'),
    ('rios africanos', 'rios-africanos'),
    ('rios brasileiros', 'rios-brasileiros'),
    ('riqueza natural', 'riqueza-natural'),
    ('risco ambiental', 'risco-ambiental'),
    ('riscos', 'riscos'),
    ('riscos geológicos', 'riscos-geológicos'),
    ('rivalidade', 'rivalidade'),
    ('rocha sedimentar', 'rocha-sedimentar'),
    ('rochas', 'rochas'),
    ('rochas magmáticas', 'rochas-magmáticas'),
    ('rochas sedimentares', 'rochas-sedimentares'),
    ('rohingya', 'rohingya'),
    ('rosa dos ventos', 'rosa-dos-ventos'),
    ('ross', 'ross'),
    ('rotas globais', 'rotas-globais'),
    ('rotação da terra', 'rotação-da-terra'),
    ('royalties do petróleo', 'royalties-do-petróleo'),
    ('ruanda', 'ruanda'),
    ('rural-urbana', 'rural-urbana'),
    ('rural-urbano', 'rural-urbano'),
    ('rússia', 'rússia'),
    ('sahel', 'sahel'),
    ('santa catarina', 'santa-catarina'),
    ('savana', 'savana'),
    ('saída', 'saída'),
    ('saída da ue', 'saída-da-ue'),
    ('saúde', 'saúde'),
    ('saúde educação renda', 'saúde-educação-renda'),
    ('segregação urbana', 'segregação-urbana'),
    ('segunda guerra mundial', 'segunda-guerra-mundial'),
    ('segunda metade do século xx', 'segunda-metade-do-século-xx'),
    ('segurança', 'segurança'),
    ('segurança alimentar', 'segurança-alimentar'),
    ('sem-terra', 'sem-terra'),
    ('semicondutores', 'semicondutores'),
    ('semiárido', 'semiárido'),
    ('sensoriamento remoto', 'sensoriamento-remoto'),
    ('separatismo', 'separatismo'),
    ('sertão nordestino', 'sertão-nordestino'),
    ('serviços', 'serviços'),
    ('setor energético', 'setor-energético'),
    ('setor industrial', 'setor-industrial'),
    ('setor primário', 'setor-primário'),
    ('setor residencial', 'setor-residencial'),
    ('setor terciário', 'setor-terciário'),
    ('setores da economia', 'setores-da-economia'),
    ('setores econômicos', 'setores-econômicos'),
    ('silvicultura', 'silvicultura'),
    ('sionismo', 'sionismo'),
    ('sistema de produção', 'sistema-de-produção'),
    ('sistema de transporte', 'sistema-de-transporte'),
    ('sistema elétrico brasileiro', 'sistema-elétrico-brasileiro'),
    ('sistema fluvial', 'sistema-fluvial'),
    ('sistema mundial', 'sistema-mundial'),
    ('sistemas agrícolas', 'sistemas-agrícolas'),
    ('sistemas de cultivo', 'sistemas-de-cultivo'),
    ('sistemas de informação geográfica', 'sistemas-de-informação-geográfica'),
    ('sistemas de projeção', 'sistemas-de-projeção'),
    ('sistemas terrestres', 'sistemas-terrestres'),
    ('smog', 'smog'),
    ('socialismo', 'socialismo'),
    ('socialismo de mercado', 'socialismo-de-mercado'),
    ('sociedade', 'sociedade'),
    ('sociedade contemporânea', 'sociedade-contemporânea'),
    ('socioeconômico', 'socioeconômico'),
    ('soft power', 'soft-power'),
    ('soja', 'soja'),
    ('solos', 'solos'),
    ('solos brasileiros', 'solos-brasileiros'),
    ('status jurídico', 'status-jurídico'),
    ('subcontinente indiano', 'subcontinente-indiano'),
    ('subdesenvolvimento', 'subdesenvolvimento'),
    ('subdesenvolvimento industrializado', 'subdesenvolvimento-industrializado'),
    ('subducção', 'subducção'),
    ('subespaços brasileiros', 'subespaços-brasileiros'),
    ('substituição de importações', 'substituição-de-importações'),
    ('substituição do petróleo', 'substituição-do-petróleo'),
    ('sudeste', 'sudeste'),
    ('sudeste asiático', 'sudeste-asiático'),
    ('sudão do sul', 'sudão-do-sul'),
    ('sul do brasil', 'sul-do-brasil'),
    ('superfície terrestre', 'superfície-terrestre'),
    ('sustentabilidade', 'sustentabilidade'),
    ('são paulo', 'são-paulo'),
    ('século xvi', 'século-xvi'),
    ('séculos xvii-xviii', 'séculos-xvii-xviii'),
    ('símbolo', 'símbolo'),
    ('síria', 'síria'),
    ('tabela geológica', 'tabela-geológica'),
    ('taiga', 'taiga'),
    ('taliban', 'taliban'),
    ('tarifas alfandegárias', 'tarifas-alfandegárias'),
    ('taxa de fecundidade', 'taxa-de-fecundidade'),
    ('taxa de urbanização', 'taxa-de-urbanização'),
    ('taylorismo', 'taylorismo'),
    ('tchetchênia', 'tchetchênia'),
    ('tecnologia', 'tecnologia'),
    ('tecnologia agrícola', 'tecnologia-agrícola'),
    ('tecnosfera', 'tecnosfera'),
    ('tectonismo', 'tectonismo'),
    ('tectônica de placas', 'tectônica-de-placas'),
    ('temperatura', 'temperatura'),
    ('temperatura nas cidades', 'temperatura-nas-cidades'),
    ('tempo geológico', 'tempo-geológico'),
    ('tendências geográficas', 'tendências-geográficas'),
    ('tensões geopolíticas', 'tensões-geopolíticas'),
    ('teocracia', 'teocracia'),
    ('teoria de weber', 'teoria-de-weber'),
    ('teoria demográfica', 'teoria-demográfica'),
    ('teoria reformista', 'teoria-reformista'),
    ('teorias demográficas', 'teorias-demográficas'),
    ('terceira revolução industrial', 'terceira-revolução-industrial'),
    ('terremotos', 'terremotos'),
    ('territorialidade', 'territorialidade'),
    ('territorialização', 'territorialização'),
    ('território', 'território'),
    ('territórios climáticos', 'territórios-climáticos'),
    ('terrorismo', 'terrorismo'),
    ('tigres asiáticos', 'tigres-asiáticos'),
    ('tipos climáticos', 'tipos-climáticos'),
    ('tipos climáticos mundiais', 'tipos-climáticos-mundiais'),
    ('tipos de chuva', 'tipos-de-chuva'),
    ('tipos de floresta', 'tipos-de-floresta'),
    ('tipos de indústria', 'tipos-de-indústria'),
    ('tipos de rocha', 'tipos-de-rocha'),
    ('tipos de solo', 'tipos-de-solo'),
    ('topografia', 'topografia'),
    ('totalidade geográfica', 'totalidade-geográfica'),
    ('toyotismo', 'toyotismo'),
    ('trabalho', 'trabalho'),
    ('trabalho de cuidado', 'trabalho-de-cuidado'),
    ('trabalho doméstico', 'trabalho-doméstico'),
    ('trabalho escravo', 'trabalho-escravo'),
    ('trabalho feminino', 'trabalho-feminino'),
    ('trabalho humano', 'trabalho-humano'),
    ('transferência da capital', 'transferência-da-capital'),
    ('transformação do espaço', 'transformação-do-espaço'),
    ('transformação econômica', 'transformação-econômica'),
    ('transformação espacial', 'transformação-espacial'),
    ('transformações', 'transformações'),
    ('transformações econômicas', 'transformações-econômicas'),
    ('transformações espaciais', 'transformações-espaciais'),
    ('transgênicos', 'transgênicos'),
    ('transição demográfica', 'transição-demográfica'),
    ('transição econômica', 'transição-econômica'),
    ('transição urbana', 'transição-urbana'),
    ('transnacionais', 'transnacionais'),
    ('transporte', 'transporte'),
    ('transporte ferroviário', 'transporte-ferroviário'),
    ('transporte marítimo', 'transporte-marítimo'),
    ('transporte rodoviário', 'transporte-rodoviário'),
    ('transportes brasileiros', 'transportes-brasileiros'),
    ('transumância', 'transumância'),
    ('tratado da antártica', 'tratado-da-antártica'),
    ('tratado de madri', 'tratado-de-madri'),
    ('tráfego aéreo', 'tráfego-aéreo'),
    ('tráfico humano', 'tráfico-humano'),
    ('tsunamis', 'tsunamis'),
    ('turquia', 'turquia'),
    ('técnica', 'técnica'),
    ('técnicas de cultivo', 'técnicas-de-cultivo'),
    ('um país dois sistemas', 'um-país-dois-sistemas'),
    ('unidade europeia', 'unidade-europeia'),
    ('unidades de conservação', 'unidades-de-conservação'),
    ('união europeia', 'união-europeia'),
    ('união soviética', 'união-soviética'),
    ('urbanismo', 'urbanismo'),
    ('urbanização', 'urbanização'),
    ('urbanização acelerada', 'urbanização-acelerada'),
    ('urbanização brasileira', 'urbanização-brasileira'),
    ('urbanização colonial', 'urbanização-colonial'),
    ('urbanização e hidrologia', 'urbanização-e-hidrologia'),
    ('urbanização mundial', 'urbanização-mundial'),
    ('urss', 'urss'),
    ('uruguai', 'uruguai'),
    ('usina hidrelétrica', 'usina-hidrelétrica'),
    ('usina hidrelétrica de itaipu', 'usina-hidrelétrica-de-itaipu'),
    ('usmca', 'usmca'),
    ('uso de agrotóxicos', 'uso-de-agrotóxicos'),
    ('uti possidetis', 'uti-possidetis'),
    ('utilização da terra', 'utilização-da-terra'),
    ('vale do silício', 'vale-do-silício'),
    ('vantagens e desvantagens', 'vantagens-e-desvantagens'),
    ('vantagens energéticas', 'vantagens-energéticas'),
    ('vazão dos rios', 'vazão-dos-rios'),
    ('vegetação', 'vegetação'),
    ('vegetação brasileira', 'vegetação-brasileira'),
    ('vegetação tropical', 'vegetação-tropical'),
    ('vegetação xerófita', 'vegetação-xerófita'),
    ('venezuela', 'venezuela'),
    ('violência no campo', 'violência-no-campo'),
    ('violência urbana', 'violência-urbana'),
    ('vulcanismo', 'vulcanismo'),
    ('vulnerabilidade', 'vulnerabilidade'),
    ('várzea', 'várzea'),
    ('wegener', 'wegener'),
    ('xenofobia', 'xenofobia'),
    ('xingu', 'xingu'),
    ('xinjiang', 'xinjiang'),
    ('zona costeira', 'zona-costeira'),
    ('zona de convergência', 'zona-de-convergência'),
    ('zona intertropical', 'zona-intertropical'),
    ('zonas polares', 'zonas-polares'),
    ('zonas sísmicas', 'zonas-sísmicas'),
    ('áfrica', 'áfrica'),
    ('áfrica austral', 'áfrica-austral'),
    ('áfrica do sul', 'áfrica-do-sul'),
    ('áfrica mediterrânea', 'áfrica-mediterrânea'),
    ('áfrica ocidental', 'áfrica-ocidental'),
    ('áfrica oriental', 'áfrica-oriental'),
    ('água doce', 'água-doce'),
    ('água potável', 'água-potável'),
    ('águas oceânicas', 'águas-oceânicas'),
    ('águas subterrâneas', 'águas-subterrâneas'),
    ('área biogeográfica', 'área-biogeográfica'),
    ('área de proteção ambiental', 'área-de-proteção-ambiental'),
    ('área destacada', 'área-destacada'),
    ('ártico', 'ártico'),
    ('ásia', 'ásia'),
    ('ásia meridional', 'ásia-meridional'),
    ('êxodo rural', 'êxodo-rural'),
    ('índia', 'índia'),
    ('índice de desenvolvimento humano', 'índice-de-desenvolvimento-humano'),
    ('índices de desenvolvimento', 'índices-de-desenvolvimento');
